using System;
using UnityEngine;

namespace Solmar
{
    /// <summary>
    /// Synthesises a Miami-style downtown ambience entirely on the audio thread: distant traffic
    /// rumble, occasional car pass-bys panned across the stereo field, gusty palm-tree wind, faint
    /// bird chirps and a faint city hum. No audio assets are involved; everything is generated by a
    /// streamed <see cref="AudioClip"/> created with <see cref="AudioClip.Create"/>.
    /// </summary>
    public sealed class CityAmbience : MonoBehaviour
    {
        [Header("Master")]
        public float masterVolume = 0.5f;

        [Header("Layer volumes")]
        public float trafficVolume = 1f;
        public float passByVolume = 1f;
        public float windVolume = 0.8f;
        public float birdVolume = 0.5f;
        [Tooltip("Two steady low tones (mains hum and a distant HVAC drone): keep it faint.")]
        public float humVolume = 0.12f;

        const int Channels = 2;
        const int SampleRate = 48000;
        // The clip is streamed and loops; its length only sets how often Unity wraps it.
        const int StreamLengthSamples = SampleRate * 10;
        const double Dt = 1.0 / SampleRate;
        const double TwoPi = Math.PI * 2.0;
        const float TrafficCutoffHz = 150f;
        const float TrafficSwellRate = 0.08f;
        const float BrownStep = 0.02f;
        const float BrownGain = 3.5f;
        const float WindBandwidthHz = 700f;
        const float PassByBandwidthHz = 800f;
        const float HumFreq1 = 60f;
        const float HumFreq2 = 133f;

        AudioSource audioSource;
        AudioClip clip;
        uint rngState;

        // Traffic rumble.
        float trafficBrown;
        float trafficLpState;
        double trafficSwellPhase;
        // Wind.
        float windLowState;
        float windHighState;
        float windGustLevel;
        float windGustTarget;
        double windGustTimer;
        float windGustSmoothCoeff;
        // City hum.
        double humPhase1;
        double humPhase2;
        // Pass-by.
        bool passByActive;
        double passByTimer;
        double passByElapsed;
        float passByDuration;
        float passByDirection;
        float passByCenterStart;
        float passByCenterEnd;
        float passByLowState;
        float passByHighState;
        // Birds.
        bool birdActive;
        bool birdInChirp;
        int birdChirpsLeft;
        double birdTimer;
        float birdSegmentDuration;
        double birdPhase;
        float birdChirpStartFreq;
        float birdChirpEndFreq;

        void OnEnable()
        {
            if (FindAnyObjectByType<AudioListener>() == null)
            {
                gameObject.AddComponent<AudioListener>();
            }

            rngState = (uint)GetInstanceID() ^ 0x9E3779B9u;
            if (rngState == 0u)
            {
                rngState = 0x9E3779B9u;
            }

            passByTimer = RandomRange(6f, 20f);
            birdTimer = RandomRange(4f, 15f);
            windGustTarget = RandomRange(0.3f, 1f);
            windGustLevel = windGustTarget;
            windGustTimer = RandomRange(1.5f, 4f);
            windGustSmoothCoeff = (float)(Dt / 0.6);

            clip = AudioClip.Create("CityAmbience", StreamLengthSamples, Channels, SampleRate, true, OnAudioRead);

            audioSource = gameObject.AddComponent<AudioSource>();
            audioSource.playOnAwake = false;
            audioSource.spatialBlend = 0f;
            audioSource.loop = true;
            audioSource.clip = clip;
            audioSource.Play();
        }

        void OnDisable()
        {
            if (audioSource != null)
            {
                audioSource.Stop();
                Destroy(audioSource);
                audioSource = null;
            }

            if (clip != null)
            {
                Destroy(clip);
                clip = null;
            }
        }

        // Runs on the audio thread: no allocations, no Unity API calls, only fields and the xorshift RNG below.
        void OnAudioRead(float[] data)
        {
            int frameCount = data.Length / Channels;

            for (int i = 0; i < frameCount; i++)
            {
                float center = 0f;

                // Traffic rumble: brown noise low-passed around 150 Hz, with a slow swell.
                float white = NextSigned();
                trafficBrown = (trafficBrown + BrownStep * white) / (1f + BrownStep);
                float trafficFiltered = OnePoleApply(trafficBrown, ref trafficLpState, OnePoleCoeff(TrafficCutoffHz));
                trafficSwellPhase += TrafficSwellRate * TwoPi * Dt;
                if (trafficSwellPhase > TwoPi)
                {
                    trafficSwellPhase -= TwoPi;
                }
                float swell = 0.65f + 0.35f * (float)Math.Sin(trafficSwellPhase);
                center += trafficFiltered * BrownGain * swell * trafficVolume;

                // Wind: gusty band-passed noise wandering through 1-4 kHz.
                windGustTimer -= Dt;
                if (windGustTimer <= 0.0)
                {
                    windGustTarget = RandomRange(0.15f, 1f);
                    windGustTimer = RandomRange(1.5f, 4f);
                }
                windGustLevel += (windGustTarget - windGustLevel) * windGustSmoothCoeff;
                float windCenterFreq = 1000f + windGustLevel * 3000f;
                float windAmp = 0.2f + 0.8f * windGustLevel;
                float windSample = BandPass(NextSigned(), ref windLowState, ref windHighState, windCenterFreq, WindBandwidthHz);
                center += windSample * windAmp * windVolume;

                // City hum: a faint low drone.
                humPhase1 += TwoPi * HumFreq1 * Dt;
                if (humPhase1 > TwoPi)
                {
                    humPhase1 -= TwoPi;
                }
                humPhase2 += TwoPi * HumFreq2 * Dt;
                if (humPhase2 > TwoPi)
                {
                    humPhase2 -= TwoPi;
                }
                float hum = (float)(Math.Sin(humPhase1) * 0.6 + Math.Sin(humPhase2) * 0.4) * 0.15f;
                center += hum * humVolume;

                // Birds: occasional, quiet FM chirp sequences.
                center += UpdateBirds() * birdVolume;

                // Pass-by: an occasional car sweeping across the stereo field.
                float passSample = UpdatePassBy(out float passLeftGain, out float passRightGain) * passByVolume;

                float left = (center + passSample * passLeftGain) * masterVolume;
                float right = (center + passSample * passRightGain) * masterVolume;

                int sampleIndex = i * Channels;
                data[sampleIndex] = (float)Math.Tanh(left);
                data[sampleIndex + 1] = (float)Math.Tanh(right);
            }
        }

        float UpdatePassBy(out float leftGain, out float rightGain)
        {
            if (!passByActive)
            {
                passByTimer -= Dt;
                if (passByTimer > 0.0)
                {
                    leftGain = 0f;
                    rightGain = 0f;
                    return 0f;
                }

                passByActive = true;
                passByElapsed = 0.0;
                passByDuration = RandomRange(3f, 6f);
                passByDirection = NextSigned() >= 0f ? 1f : -1f;
                passByCenterStart = RandomRange(1400f, 2000f);
                passByCenterEnd = RandomRange(400f, 700f);
            }
            else
            {
                passByElapsed += Dt;
            }

            float progress = (float)(passByElapsed / passByDuration);
            if (progress >= 1f)
            {
                passByActive = false;
                passByTimer = RandomRange(6f, 20f);
                leftGain = 0f;
                rightGain = 0f;
                return 0f;
            }

            float envelope = (float)Math.Sin(Math.PI * progress);
            float centerFreq = passByCenterStart + (passByCenterEnd - passByCenterStart) * progress;
            float noise = BandPass(NextSigned(), ref passByLowState, ref passByHighState, centerFreq, PassByBandwidthHz);
            float pan = passByDirection * (progress * 2f - 1f);
            EqualPowerPan(pan, out leftGain, out rightGain);
            return noise * envelope;
        }

        float UpdateBirds()
        {
            if (!birdActive)
            {
                birdTimer -= Dt;
                if (birdTimer > 0.0)
                {
                    return 0f;
                }

                birdActive = true;
                birdChirpsLeft = 2 + (int)(NextUnit() * 3f);
                StartBirdChirp();
                return 0f;
            }

            if (!birdInChirp)
            {
                birdTimer -= Dt;
                if (birdTimer <= 0.0)
                {
                    StartBirdChirp();
                }
                return 0f;
            }

            birdTimer -= Dt;
            float progress = Clamp01(1f - (float)(birdTimer / birdSegmentDuration));
            float freq = birdChirpStartFreq + (birdChirpEndFreq - birdChirpStartFreq) * progress;
            birdPhase += TwoPi * freq * Dt;
            if (birdPhase > TwoPi)
            {
                birdPhase -= TwoPi;
            }
            float envelope = (float)Math.Sin(Math.PI * progress);
            float sample = (float)Math.Sin(birdPhase) * envelope * 0.5f;

            if (birdTimer <= 0.0)
            {
                birdChirpsLeft--;
                if (birdChirpsLeft > 0)
                {
                    birdInChirp = false;
                    birdTimer = RandomRange(0.08f, 0.22f);
                }
                else
                {
                    birdActive = false;
                    birdTimer = RandomRange(4f, 15f);
                }
            }

            return sample;
        }

        void StartBirdChirp()
        {
            birdInChirp = true;
            birdSegmentDuration = RandomRange(0.06f, 0.14f);
            birdTimer = birdSegmentDuration;
            birdPhase = 0.0;
            birdChirpStartFreq = RandomRange(2500f, 4200f);
            float span = RandomRange(500f, 1500f);
            float end = birdChirpStartFreq + (NextUnit() < 0.5f ? span : -span);
            if (end < 2500f) end = 2500f;
            if (end > 6000f) end = 6000f;
            birdChirpEndFreq = end;
        }

        // Small xorshift32 RNG: cheap, allocation-free and safe to call from the audio thread.
        uint NextUint()
        {
            uint x = rngState;
            x ^= x << 13;
            x ^= x >> 17;
            x ^= x << 5;
            rngState = x;
            return x;
        }

        float NextUnit()
        {
            return NextUint() * (1f / 4294967296f);
        }

        float NextSigned()
        {
            return NextUnit() * 2f - 1f;
        }

        float RandomRange(float min, float max)
        {
            return min + NextUnit() * (max - min);
        }

        static float OnePoleCoeff(float cutoffHz)
        {
            double w = Math.Exp(-TwoPi * cutoffHz * Dt);
            return (float)(1.0 - w);
        }

        static float OnePoleApply(float x, ref float state, float coeff)
        {
            state += coeff * (x - state);
            return state;
        }

        static float BandPass(float x, ref float lowState, ref float highState, float centerHz, float bandwidthHz)
        {
            float half = bandwidthHz * 0.5f;
            float lo = OnePoleApply(x, ref lowState, OnePoleCoeff(centerHz - half));
            float hi = OnePoleApply(x, ref highState, OnePoleCoeff(centerHz + half));
            return hi - lo;
        }

        static void EqualPowerPan(float pan, out float left, out float right)
        {
            float p = (pan + 1f) * 0.25f * (float)Math.PI;
            left = (float)Math.Cos(p);
            right = (float)Math.Sin(p);
        }

        static float Clamp01(float v)
        {
            if (v < 0f) return 0f;
            if (v > 1f) return 1f;
            return v;
        }
    }
}
